pipeline {
  agent any

  environment {
    AWS_DEFAULT_REGION    = "us-east-1"
    AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
    AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    AWS_SESSION_TOKEN     = credentials('AWS_SESSION_TOKEN')
    KUBECONFIG            = "/var/jenkins_home/.kube/config"
  }

  stages {
    stage("Checkout") {
      steps { checkout scm }
    }

    stage("Validate") {
      steps {
        dir("terraform") {
          sh "terraform init -input=false"
          sh "terraform fmt -check"
          sh "terraform validate"
        }
      }
    }

    stage("Import existing resources") {
    steps {
      dir("terraform") {
        sh '''
          set -eu

          import_if_absent () {
            address="$1"
            resource_id="$2"

            if terraform state list | grep -Fxq "$address"; then
              echo "$address est deja present dans le state Terraform."
            else
              echo "Import de $address ..."
              terraform import -input=false "$address" "$resource_id"
            fi
          }

          import_if_absent "module.ecs.aws_ecr_repository.app" "demo-app"

          SECURITY_GROUP_ID=$(aws ec2 describe-security-groups \
            --region "$AWS_DEFAULT_REGION" \
            --filters \
              "Name=group-name,Values=demo-svc-sg" \
              "Name=vpc-id,Values=vpc-0bbfc74522592e3fb" \
            --query "SecurityGroups[0].GroupId" \
            --output text)

          test -n "$SECURITY_GROUP_ID"
          test "$SECURITY_GROUP_ID" != "None"

          import_if_absent "module.ecs.aws_security_group.svc_sg" "$SECURITY_GROUP_ID"

          import_if_absent "module.k8s.kubernetes_config_map.app_config" "default/demo-app-config"
          import_if_absent "module.k8s.kubernetes_deployment.app" "default/demo-app"
          import_if_absent "module.k8s.kubernetes_service.app" "default/demo-app-svc"
        '''
      }
    }
  }

    stage("Plan") {
      steps {
        dir("terraform") {
          sh "terraform plan -out=tfplan -input=false"
          sh "terraform show -no-color tfplan | tee tfplan.txt"
        }
        archiveArtifacts artifacts: "terraform/tfplan.txt"
      }
    }

    stage("Approve") {
      steps {
        input message: "Appliquer ECS + Kubernetes ?", ok: "Apply"
      }
    }

    stage("Apply") {
      steps {
        dir("terraform") {
          sh "terraform apply -input=false tfplan"
        }
      }
    }

    stage("Verify") {
      steps {
        sh "aws ecs describe-services --cluster demo-cluster --services demo-app-service"
        sh "kubectl get pods,svc,hpa"
      }
    }
  }

  post {
    always {
      dir("terraform") { sh "rm -f tfplan" }
    }
  }
}
